#!/bin/bash

WALL_DIR="$HOME/.config/fastfetch/ascii_arts/"

# Set this to anything not valid to use the default image
SET="default"

if [ -d $WALL_DIR$SET ]
then
    RND_IMG=$(ls $WALL_DIR$SET | shuf -n 1)

    IMG_PATH="${WALL_DIR}${SET}/${RND_IMG}"
    fastfetch --load-config ${HOME}/.config/fastfetch/config.conf --logo ${IMG_PATH}
else
    fastfetch --load-config ${HOME}/.config/fastfetch/config.conf
fi


