#!/bin/sh

if [ -f "/etc/modprobe.d/blacklist-nvidia.conf" ] && [ -f "/etc/udev/rules.d/00-remove-nvidia.rules" ]; then
    sudo mv "/etc/modprobe.d/blacklist-nvidia.conf" "/etc/modprobe.d/blacklist-nvidia.conf.disabled"
    sudo mv "/etc/udev/rules.d/00-remove-nvidia.rules" "/etc/udev/rules.d/00-remove-nvidia.rules.disabled"
    echo "The GPU will be enabled after reboot."
    exit 0
elif [ -f "/etc/modprobe.d/blacklist-nvidia.conf.disabled" ] && [ -f "/etc/udev/rules.d/00-remove-nvidia.rules.disabled" ]; then
    sudo mv "/etc/modprobe.d/blacklist-nvidia.conf.disabled" "/etc/modprobe.d/blacklist-nvidia.conf"
    sudo mv "/etc/udev/rules.d/00-remove-nvidia.rules.disabled" "/etc/udev/rules.d/00-remove-nvidia.rules"
    echo "The GPU will be disabled after reboot."
    exit 0
else
    echo "The configurations don't match.
    
    Check /etc/modprobe.d/blacklist-nvidia.conf and /etc/udev/rules.d/00-remove-nvidia.rules."
    exit 1
fi
